# MAKEFILE FOR ZIPPING AND DELETING ZIPED FILES


# Comment line below if you want make to be in verbose mode
MAKEFLAGS += --silent


# ARGUMENT CATCHING
num=$(filter-out $@, $(MAKECMDGOALS))
# this sould get the arguments of make -> num of sending
subject=hada
NAME=$(subject)-p$(num)
pMSG="PROJECT CREATED AND INICIALIZED... WAITING SYNCRONIZATION"

make:
% : ;

start:
	mkdir $(NAME)
	@echo ".vs #IGNORING VISUAL STUDIO PACKAGES" > .gitignore
	@echo "##AUTOGENERATED README WHILE USING MAKEFILE   #THIS FILE IS INTENDED TO CONTAIN A LITLE ABSTRACT ABOUT THE CONTENT OF THE GIT REPOSITORY.  " > README.md	
	mv README.md $(NAME)/README.md
	mv .gitignore $(NAME)/.gitignore
	cd $(NAME) && git init && git add * && git commit -m $(pMSG)
	@echo $(pMSG)
	@echo "TRY: git remote add [remote_tarjet] THEN git push -u [remote_tarjet_configured_name] [local_branch_to_syncro]"
	@echo "IF NO REMOTE BRANCH IS CONFIGURED, TRY: git stash"
	@echo "IF YOU WANT TO DOWNLOAD AND SYNCRONIZE AN EXISTING REPOSITORY THEN TRY: make sync [repo_address]"
	@echo "  "
	@echo "ALL WORKS DONE... DO: cd $(NAME) TO START WORKING"
% : ;

upload:
	git add .
	git commit -m "num"
	git push -u online master
% : ;

zip:
	zip -r $(NAME).zip $(NAME)
% : ;

clean: 
	rm -r -f --interactive=never $(NAME) $(NAME).zip
% : ;

# EMPTY works:
% : ;
